apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: block-buster-ingress
  namespace: 2-demo
  annotations:
    kubernetes.io/ingress.class: nginx  # Explicitly set the Ingress class
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: block-buster-service
            port: 
              number: 80  # Changed back to 80 as Ingress typically handles standard HTTP ports